# Generated by Django 4.2.5 on 2023-09-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_tegpost_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TegPost',
            new_name='Teg',
        ),
    ]
