# Generated by Django 4.2.5 on 2023-10-07 07:36

from django.db import migrations
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to='catalog/product/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
